sudo: required
services:
  - docker

before_install:
  - docker build -t cyyeh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cyyeh/react-test npm test -- --coverage

after_success:
  - docker build -t cyyeh/multi-docker-client ./client
  - docker build -t cyyeh/multi-docker-nginx ./nginx
  - docker build -t cyyeh/multi-docker-server ./server
  - docker build -t cyyeh/multi-docker-worker ./worker

