sudo: required
services:
  - docker

before_install:
  - docker build -t chihyu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chihyu/react-test npm test -- --coverage

after_success:
  - docker build -t chihyu/multi-docker-client ./client
  - docker build -t chihyu/multi-docker-nginx ./nginx
  - docker build -t chihyu/multi-docker-server ./server
  - docker build -t chihyu/multi-docker-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push chihyu/multi-docker-client
  - docker push chihyu/multi-docker-nginx
  - docker push chihyu/multi-docker-server
  - docker push chihyu/multi-docker-worker